### ISSUE TITLE
install box86

### ISSUE THREAD

**Issue by matiasOliva64** [kamehame-ha/steamcmd-on-arm64#1]
Hi, I follow the steps to install box86 and box64, they install correctly but when I run ./steamcmd.sh I get the following error: ./steamcmd.sh: line 37: /home/ubuntu/steamcmd/linux32/steamcmd: No such file or directory
and if I also write box86 in the console it takes the binary but I get this error:
-bash: /usr/local/bin/box86: No such file or directory
By the way, I use an oracle cloud vps with an arm processor, which is always free

**Comment by matiasOliva64** [comment]
Fixed, missing libc6:armhf library

**Comment by kamehame-ha** [comment]
I'm glad you made it, also thanks for using my tutorial

**Comment by kamehame-ha** [comment]
I'm glad you made it, also thanks for using my tutorial
