### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by matiasOliva64** [kamehame-ha/steamcmd-on-arm64#2]
A question. I was testing the server and the server works fine, but it stays online for approximately 1 day and 5 hours, then when I try to connect it stays connected and in the server console via ssh/putty it stays static, but the process keeps running and I have to shut down with ctrl + c (I use screen session). I wanted to know if you have had this problem?

**Comment by kamehame-ha** [comment]
Never had that issue, what game server you trying to run?

**Comment by matiasOliva64** [comment]
I'm running a rust server

**Comment by kamehame-ha** [comment]
well it looks like its rust issue, not the method
